In [2]:
from selenium import webdriver

## Quiz 1
- 아래 URL의 NBA 데이터를 크롤링하여 판다스 데이터 프레임으로 나타내세요.
- http://stats.nba.com/teams/traditional/?sort=GP&dir=-1

In [78]:
driver = webdriver.Chrome()

In [79]:
url = "http://stats.nba.com/teams/traditional/?sort=GP&dir=-1"

In [80]:
driver.get(url)

링크로 들어가면 GP로 정렬되어 있는 상태임  
![]()

In [92]:
# column이름을 list로 받아오기
columns = driver.find_elements_by_css_selector("div.nba-stat-table__overflow > table > thead > tr > th")[:28]
len(columns)

28

In [93]:
ls_column = []
for column in columns:
    ls_column.append(column.text)
    
ls_column

['',
 'TEAM',
 'GP',
 'W',
 'L',
 'WIN%',
 'MIN',
 'PTS',
 'FGM',
 'FGA',
 'FG%',
 '3PM',
 '3PA',
 '3P%',
 'FTM',
 'FTA',
 'FT%',
 'OREB',
 'DREB',
 'REB',
 'AST',
 'TOV',
 'STL',
 'BLK',
 'BLKA',
 'PF',
 'PFD',
 '+/-']

In [112]:
df = pd.DataFrame(columns = ls_column)
df

Empty DataFrame
Columns: [, TEAM, GP, W, L, WIN%, MIN, PTS, FGM, FGA, FG%, 3PM, 3PA, 3P%, FTM, FTA, FT%, OREB, DREB, REB, AST, TOV, STL, BLK, BLKA, PF, PFD, +/-]
Index: []

[0 rows x 28 columns]

In [96]:
# 팀마다의 stat, 즉 표의 각 행을 team_stat으로 저장함
team_stat = driver.find_elements_by_css_selector("div.nba-stat-table__overflow > table > tbody > tr")
len(team_stat)

35

In [121]:
for stat in team_stat:
    stats = stat.find_elements_by_css_selector("td")
    stat = {}
    for i in range(len(stats)):
        stat[ls_column[i]] = stats[i].text
    df.loc[len(df)] = stat
df

,,TEAM,GP,W,L,WIN%,MIN,PTS,FGM,FGA,...,DREB,REB,AST,TOV,STL,BLK,BLKA,PF,PFD,+/-
0,1,Charlotte Hornets,3,2,1,.667,48.0,112.7,38.0,84.0,...,43.3,49.0,24.0,15.3,5.3,7.3,5.7,24.0,29.7,4.3
1,1,Los Angeles Lakers,3,1,2,.333,48.0,115.3,41.3,83.0,...,35.3,41.0,24.3,21.0,9.0,6.7,4.0,28.7,32.3,-4.7
2,1,Boston Celtics,3,1,2,.333,48.0,102.3,37.7,93.7,...,40.0,50.0,18.3,12.3,8.3,6.7,5.3,30.7,24.0,-3.7
3,4,Minnesota Timberwolves,2,1,1,.500,48.0,107.5,34.5,87.5,...,32.5,42.5,13.5,16.5,7.5,7.5,8.0,20.5,30.5,-11.5
4,4,Denver Nuggets,2,2,0,1.000,48.0,118.5,40.0,85.5,...,32.5,45.0,27.0,23.5,12.0,4.5,7.0,26.5,30.5,9.5
5,4,Houston Rockets,2,1,1,.500,48.0,115.5,37.5,80.0,...,33.0,41.0,23.0,24.0,11.0,7.5,4.0,31.5,31.5,3.0
6,4,LA Clippers,2,2,0,1.000,48.0,119.0,45.0,89.0,...,37.0,45.5,33.5,16.5,8.5,7.5,5.5,32.0,25.5,23.0
7,4,Miami Heat,2,0,2,.000,48.0,106.5,37.0,94.5,...,36.5,52.0,20.0,16.0,9.0,4.5,8.0,27.5,30.0,-6.5
8,4,Chicago Bulls,2,1,1,.500,48.0,105.0,41.0,100.5,...,38.0,47.5,23.0,9.5,7.5,3.0,7.0,19.5,18.0,-11.0
9,4,New Orleans Pelicans,2,0,2,.000,48.0,109.0,41.0,100.5,...,38.5,49.5,24.5,18.0,5.0,5.5,8.0,23.5,24.0,-13.0
10,4,New York Knicks,2,2,0,1.000,50.5,115.5,38.5,85.0,...,40.5,50.0,19.5,22.5,11.0,6.5,5.0,36.5,34.5,4.0
11,4,Philadelphia 76ers,2,2,0,1.000,48.0,112.0,39.5,83.0,...,36.0,48.0,25.0,18.5,8.5,8.0,2.5,24.5,29.5,13.0
12,4,Phoenix Suns,2,1,1,.500,48.0,96.5,31.5,75.5,...,37.0,48.0,20.5,20.0,7.5,9.0,4.5,32.0,28.5,0.5
13,4,Sacramento Kings,2,1,1,.500,48.0,114.5,42.0,90.5,...,31.5,40.5,25.5,16.0,6.5,3.5,5.0,38.0,29.0,-0.5
14,4,Toronto Raptors,2,1,1,.500,48.0,106.0,34.0,89.0,...,35.5,48.5,13.0,18.5,8.5,5.5,4.0,28.5,35.5,1.5
15,4,Utah Jazz,2,2,0,1.000,48.0,117.5,44.0,89.5,...,47.0,56.5,28.5,19.0,8.5,5.5,3.0,27.0,27.0,36.5
16,17,Memphis Grizzlies,1,0,1,.000,48.0,115.0,40.0,85.0,...,27.0,40.0,24.0,23.0,11.0,2.0,7.0,37.0,34.0,-16.0
17,17,Beijing Ducks,1,0,1,.000,48.0,63.0,17.0,71.0,...,22.0,33.0,12.0,17.0,4.0,2.0,10.0,32.0,29.0,-53.0
18,17,Milwaukee Bucks,1,1,0,1.000,48.0,116.0,44.0,89.0,...,53.0,64.0,28.0,13.0,3.0,7.0,2.0,12.0,19.0,34.0
19,17,Atlanta Hawks,1,1,0,1.000,48.0,116.0,48.0,105.0,...,44.0,54.0,32.0,18.0,7.0,12.0,4.0,28.0,23.0,14.0
20,17,Detroit Pistons,1,1,0,1.000,48.0,97.0,39.0,84.0,...,35.0,45.0,19.0,16.0,6.0,5.0,3.0,30.0,25.0,6.0
21,17,Golden State Warriors,1,0,1,.000,48.0,110.0,44.0,93.0,...,41.0,48.0,33.0,17.0,9.0,8.0,6.0,23.0,16.0,-4.0
22,17,New Zealand Breakers,1,0,1,.000,48.0,86.0,31.0,87.0,...,32.0,43.0,16.0,14.0,9.0,5.0,14.0,25.0,31.0,-5.0
23,17,Oklahoma City Thunder,1,0,1,.000,48.0,91.0,30.0,82.0,...,33.0,47.0,21.0,16.0,6.0,3.0,5.0,25.0,30.0,-6.0
24,17,Orlando Magic,1,0,1,.000,48.0,114.0,45.0,91.0,...,30.0,35.0,27.0,12.0,6.0,4.0,7.0,33.0,30.0,-6.0
25,17,Perth Wildcats,1,0,1,.000,48.0,72.0,23.0,85.0,...,30.0,41.0,12.0,19.0,9.0,1.0,5.0,25.0,28.0,-58.0
26,17,Brooklyn Nets,1,0,1,.000,48.0,102.0,37.0,95.0,...,29.0,45.0,21.0,18.0,12.0,3.0,11.0,30.0,29.0,-5.0
27,17,Indiana Pacers,1,1,0,1.000,48.0,110.0,40.0,91.0,...,35.0,48.0,18.0,21.0,11.0,6.0,8.0,26.0,29.0,10.0
28,17,Portland Trail Blazers,1,0,1,.000,48.0,104.0,37.0,88.0,...,35.0,46.0,25.0,24.0,4.0,2.0,6.0,45.0,28.0,-18.0
29,17,Cleveland Cavaliers,1,1,0,1.000,48.0,102.0,33.0,80.0,...,36.0,49.0,13.0,18.0,8.0,4.0,7.0,30.0,30.0,7.0
30,17,San Antonio Spurs,1,1,0,1.000,48.0,104.0,37.0,85.0,...,39.0,48.0,23.0,22.0,8.0,6.0,5.0,30.0,28.0,4.0
31,17,Sydney Kings,1,0,1,.000,48.0,91.0,35.0,79.0,...,36.0,46.0,19.0,26.0,4.0,2.0,7.0,26.0,26.0,-19.0
32,17,Dallas Mavericks,1,1,0,1.000,48.0,116.0,39.0,75.0,...,39.0,51.0,31.0,13.0,6.0,10.0,2.0,29.0,32.0,53.0
33,17,Melbourne United,1,0,1,.000,48.0,84.0,31.0,82.0,...,29.0,37.0,15.0,23.0,10.0,1.0,9.0,26.0,19.0,-20.0
34,17,Washington Wizards,1,0,1,.000,53.0,121.0,40.0,97.0,...,44.0,57.0,25.0,24.0,10.0,7.0,2.0,39.0,44.0,-3.0

In [122]:
driver.quit()

## Quiz 2
- Selenium을 이용하여 네이버 IT/과학 기사의 10 페이지 까지의 최신 제목 리스트를 크롤링하세요.
- http://news.naver.com/main/main.nhn?mode=LSD&mid=shm&sid1=105

In [71]:
driver = webdriver.Chrome()

In [72]:
def make_url(page=1):
    return "http://news.naver.com/main/main.nhn?mode=LSD&mid=shm&sid1=105#&date=%2000:00:00&page="\
 + str(page)

In [73]:
url = make_url()

In [74]:
driver.get(url)

#### 1페이지의 기사 리스트 가져오기
- 한 페이지에 20개의 기사가 있음

In [75]:
articles = driver.find_elements_by_css_selector("#section_body > ul > li")
len(articles)

20

#### 1페이지 안의 기사 제목 가져오기

In [76]:
dict_list = []
for article in articles:
    dict_list.append({
        "title": article.find_element_by_css_selector("dt:nth-child(2)").text     
    })
df = pd.DataFrame(dict_list)
df.tail()

                               title
15    이동전화 소비자불만 '최다'…소비자불만 1위 이통사는?
16        네안데르탈인, 현대인류에게 병도 주고 약도 줬다
17  美 컨슈머리포트 "갤노트9 배터리, 아이폰Xs 보다 우수"
18    LG 스마트폰 또 1천억원대 적자…적자 폭은 줄어든 듯
19               닌텐도, 차세대 비디오 게임기 개발

#### 1-10페이지에서 기사 제목 가져오기
- 2페이지와 7페이지에서 에러가 발생해서 try & except 처리함

In [68]:
dict_list = []

for i in range(1, 11):
    driver.get(make_url(i))
    articles = driver.find_elements_by_css_selector("#section_body > ul > li")
    print(len(articles))
    try:
        for article in articles:
            dict_list.append({"title": article.find_element_by_css_selector("dl > dt:nth-child(2)").text})
    except: 
        print(str(i)+"페이지 에러 발생")
        
df = pd.DataFrame(dict_list)
df.tail()

20
20
2페이지 에러 발생
20
20
20
20
20
7페이지 에러 발생
20
20
20

                                          title
163                iOS 12.1에서 아이폰XS 충전 문제 해결될 듯
164                    박원순 "서울, 블록체인 중심 되게 하겠다"
165  [人사이트]유인상 LG CNS 단장 "스마트시티, 데이터와 시민참여가 핵심"
166         [와우! 과학] 여성이 남성보다 오래 사는 이유 찾았다 (연구)
167         "V40, 카메라 기능 역랑 집중해 고객 편의최대한 끌어올렸다"

In [77]:
driver.quit()